Add inline grid-area names for form fields
Foodee/ember-foxy-forms pull request #304
Opened 2023-03-02 22:08 UTC by hew

2023-03-03 00:47 UTC, jayseo5953 commented on addon/components/field-for.js
> +    return `grid-area: ${this.args.gridAreaName ?? this._dasherizedParams}`
it is a bit awkward to name an arg as gridArea but make it required to have "grid-area" in the string.
it can take ANY inline style in the way you have it now.

2023-03-03 01:12 UTC, joegaudet commented on addon/components/field-for.js
> +    return `grid-area: ${this.args.gridAreaName ?? this._dasherizedParams}`
@jayseo5953 you can't make an html safe string inline unfortunately.

2023-03-03 01:12 UTC, joegaudet commented on addon/components/field-for.js
> +    return `grid-area: ${this.args.gridAreaName ?? this._dasherizedParams}`
You could use this: https://github.com/jelhan/ember-style-modifier

2023-03-03 01:22 UTC, jayseo5953 commented on addon/components/field-for.js
> +    return `grid-area: ${this.args.gridAreaName ?? this._dasherizedParams}`
I see. yeah sure we could use that but mainly pointing out that the arg name being specific to girdArea while it actually accept any inline style not just grid-area

2023-03-03 18:36 UTC, hew commented on addon/components/field-for.js
> +    return `grid-area: ${this.args.gridAreaName ?? this._dasherizedParams}`
@jayseo5953 You are making a good point. Do you have any ideas on how to enforce the prop as being more strict?

2023-03-04 01:13 UTC, jayseo5953 commented on addon/components/field-for.js
> +    return `grid-area: ${this.args.gridAreaName ?? this._dasherizedParams}`
one minor comment, since you defined gridAreaName u sing arg decorator, u can simply reference it without `arg`.
so that u can do this.gridAreaName

2023-03-04 01:24 UTC, jayseo5953 commented on addon/components/field-for.js
> +    return `grid-area: ${this.args.gridAreaName ?? this._dasherizedParams}`
Also already posted in the slack thread but
we probably not need to expose the arg since the component already has `...attributes` this will override the html attributes when an attribute is specificied when invoking the component

```
// field-for.hbs
<Tag
  style={{html-safe this.gridArea}}
  ...attributes
/>

// invoking the component but with custom grid-area
<f.field @for='phoneNumber style={{html-safe 'grid-area: phone'}}/>
```

2023-03-09 18:52 UTC, joegaudet requested changes
Looks good, just a few comments.

Also please update the forms.md with a paragraph on the usage with an example.

2023-03-09 18:52 UTC, joegaudet commented on addon/components/form-button.js
> +  gridAreaDisabled = false;
This should be derived from the configuration (seem use bem classes), I think it should also be opt in, not opt out. Maybe useGridTemplate?

2023-03-09 18:52 UTC, joegaudet commented on addon/components/form-button.hbs
> +  {{style grid-area=this.gridArea}}
Should have a test.

2023-03-09 18:52 UTC, joegaudet commented on addon/components/field-for.hbs
> +    {{style grid-area=this.gridArea}}
Should have a test

2023-03-09 23:07 UTC, closed without merging